server:
  port: 8090
spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      username: postgres 
      password: root
      url: jdbc:postgresql://localhost:5432/persona

  jpa:
     hibernate:
       ddl-auto: none
     properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
         jdbc:
          lob:
            non_contextual_creation: true
     show-sql: 'true'
     open-in-view: true